import type { Product, Category, Sale, DashboardStats } from "../types"

export const mockCategories: Category[] = [
  { id: "1", tenantId: 1, name: "Bebidas", createdAt: new Date(), updatedAt: new Date() },
  { id: "2", tenantId: 1, name: "Snacks", createdAt: new Date(), updatedAt: new Date() },
  { id: "3", tenantId: 1, name: "Lácteos", createdAt: new Date(), updatedAt: new Date() },
  { id: "4", tenantId: 1, name: "Panadería", createdAt: new Date(), updatedAt: new Date() },
  { id: "5", tenantId: 1, name: "Limpieza", createdAt: new Date(), updatedAt: new Date() },
  { id: "1-1", tenantId: 1, name: "Gaseosas", parentId: "1", createdAt: new Date(), updatedAt: new Date() },
  { id: "1-2", tenantId: 1, name: "Jugos", parentId: "1", createdAt: new Date(), updatedAt: new Date() },
  { id: "1-3", tenantId: 1, name: "Agua", parentId: "1", createdAt: new Date(), updatedAt: new Date() },
  { id: "2-1", tenantId: 1, name: "Papas", parentId: "2", createdAt: new Date(), updatedAt: new Date() },
  { id: "2-2", tenantId: 1, name: "Galletas", parentId: "2", createdAt: new Date(), updatedAt: new Date() },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    tenantId: 1,
    name: "Coca-Cola 500ml",
    barcode: "7790895000423",
    categoryId: "1",
    subcategoryId: "1-1",
    purchasePrice: 800,
    salePrice: 1200,
    stock: 48,
    minStock: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    tenantId: 1,
    name: "Pepsi 500ml",
    barcode: "7791813420491",
    categoryId: "1",
    subcategoryId: "1-1",
    purchasePrice: 750,
    salePrice: 1000000,
    stock: 36,
    minStock: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    tenantId: 1,
    name: "Agua Mineral 1.5L",
    barcode: "7790315000125",
    categoryId: "1",
    subcategoryId: "1-3",
    purchasePrice: 400,
    salePrice: 700,
    stock: 24,
    minStock: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    tenantId: 1,
    name: "Papas Lays Classic 150g",
    barcode: "7790310000456",
    categoryId: "2",
    subcategoryId: "2-1",
    purchasePrice: 900,
    salePrice: 1500,
    stock: 20,
    minStock: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    tenantId: 1,
    name: "Galletas Oreo 118g",
    barcode: "7622300315061",
    categoryId: "2",
    subcategoryId: "2-2",
    purchasePrice: 600,
    salePrice: 950,
    stock: 30,
    minStock: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    tenantId: 1,
    name: "Leche Entera 1L",
    barcode: "7790070000789",
    categoryId: "3",
    purchasePrice: 500,
    salePrice: 850,
    stock: 5,
    minStock: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    tenantId: 1,
    name: "Pan Lactal",
    barcode: "7790080000234",
    categoryId: "4",
    purchasePrice: 800,
    salePrice: 1300,
    stock: 3,
    minStock: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    tenantId: 1,
    name: "Jugo de Naranja 1L",
    barcode: "7790090000567",
    categoryId: "1",
    subcategoryId: "1-2",
    purchasePrice: 700,
    salePrice: 1100,
    stock: 18,
    minStock: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockSales: Sale[] = [
  {
    id: "s1",
    tenantId: 1,
    userId: "u1",
    items: [
      { productId: "1", productName: "Coca-Cola 500ml", quantity: 2, unitPrice: 1200, total: 2400 },
      { productId: "4", productName: "Papas Lays Classic 150g", quantity: 1, unitPrice: 1500, total: 1500 },
    ],
    subtotal: 3900,
    tax: 0,
    total: 3900,
    paymentMethod: "cash",
    status: "completed",
    createdAt: new Date(),
  },
  {
    id: "s2",
    tenantId: 1,
    userId: "u1",
    items: [
      { productId: "6", productName: "Leche Entera 1L", quantity: 2, unitPrice: 850, total: 1700 },
      { productId: "7", productName: "Pan Lactal", quantity: 1, unitPrice: 1300, total: 1300 },
    ],
    subtotal: 3000,
    tax: 0,
    total: 3000,
    paymentMethod: "card",
    status: "completed",
    createdAt: new Date(Date.now() - 86400000),
  },
]

export const mockDashboardStats: DashboardStats = {
  todaySales: 15,
  todayRevenue: 45600,
  weekRevenue: 285400,
  monthRevenue: 1250000,
  lowStockProducts: 2,
  totalProducts: 8,
}
